-- Suppression des tables si elles existent (pour pouvoir relancer le script)
DROP TABLE invoice_row CASCADE CONSTRAINTS;
DROP TABLE invoice CASCADE CONSTRAINTS;
DROP TABLE product CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE app_user CASCADE CONSTRAINTS;

-- Table des utilisateurs (pour la connexion)
CREATE TABLE app_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL, -- Sera hashé par BCrypt
    role VARCHAR2(20) CHECK (role IN ('ADMIN', 'CLIENT'))
);

-- Table des clients (liée à un utilisateur)
CREATE TABLE customer (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    corporate_name VARCHAR2(100),
    address VARCHAR2(255),
    user_id NUMBER REFERENCES app_user(id)
);

-- Table des produits
CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(100),
    unit_price NUMBER(10,2),
    category VARCHAR2(50)
);

-- Table des factures
CREATE TABLE invoice (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE,
    invoiced_at DATE, -- Nul si état 'Créé'
    paid_at DATE,     -- Nul si pas encore 'Payé'
    customer_id NUMBER REFERENCES customer(id)
);

-- Table de liaison (Lignes de facture)
CREATE TABLE invoice_row (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity NUMBER NOT NULL,
    invoice_id NUMBER REFERENCES invoice(id),
    product_id NUMBER REFERENCES product(id)
);