spring.application.name=invoice-app

# Configuration de la connexion Oracle
# Connexion à la base de données Oracle Docker
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=billing
spring.datasource.password=billing
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# "validate" vérifie que vos classes Java correspondent exactement à vos tables SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true